---
title: "Data_Analysis Project"
author: "Musa Bah and Lily Mitchell"
bibliography: references.bib
csl: apa-numeric-superscript.csl
format:
  html:
    embed-resources: true
    df-print: paged
    tbl-cap-location: bottom
execute: 
  echo: false
  warning: false
  message: false
knitr:
  opts_chunk: 
    dev: svg
    cache: true
---

```{r}
#| label: libraries
library(tidyverse)
library(janitor)
library(moderndive)
library(knitr)
library(gridExtra)
library(GGally)
```

### Core Requirements 

Your analysis must also include at least one hypothesis test that supports an
inference about how your outcome variable is related to your explanatory
variable(s) in the population.
● For example, you may include a hypothesis test for a difference in means, a
hypothesis test for a difference in proportions, or a hypothesis test on the
coefficients of a regression model.
● You may use either randomization-based hypothesis tests (e.g., a
permutation test) or a parametric hypothesis tests (e.g., a t-test).

Your data analysis project will address a question like “How is {Variable X} related
to {Variable Y}?”.
● This means that your data set must measure several variables
● You must choose one variable to serve as your outcome variable
● You must choose another variable (or variables) to serve as explanatory
variable(s).

Your report should also cite at least one outside source of information (in addition to citing the source of your data), though that source does not necessarily have to be a peer-reviewed “academic” article.

# Introduction

Introduction: an overview of your project. In a few paragraphs, you should explain
clearly and precisely what your research question is, why it is interesting, and what
contribution you have made towards answering that question. You should give an
overview of the specifics of your model, but not the full details. Most readers never
make it past the introduction, so this is your chance to hook the reader, and is in many
ways the most important part of the paper!

Introduces the topic of your analysis (including your research question(s) and
the goals of your data analysis)
● Explains the nature of the data you are analyzing in sufficient detail
● Explains what analyses are performed and what can be learned from them
● Ends with overall conclusions related to your research question that are
supported by your data analysis.

## Data 

Data: a brief description of your data set. This section should introduce the reader to
the data by answering questions such as: what variables are included? Where did they
come from? What are units of measurement? What is the population that was
sampled? How was the sample collected? This section should also acquaint the reader
with your data set through the use of univariate and multivariate visualizations, and
univariate and multivariate summaries.

This section should aldo describe any important “data wrangling” (e.g., filtering missing
values, recoding variables) you did throughout the course of your analysis. The key
word here is “important”. Identifying what is important can be difficult at first. Try
asking yourself these guiding questions to help you decide:
◦ Could my conclusions be different I had/had not done this part of my data
wrangling?
◦ Is it reasonable that a reader could view my work differently if they knew, or didn't
know about this?"
For example
◦ Could my conclusions be different I had/had not removed missing observations?
Yes, definitely, so it should be described.
◦ Could my conclusions be different if I described how the missing observations
were removed? Probably not (using dplyr::filter has the same overall consequences
as deleting rows in a spreadsheet, so it’s not worth mentioning)
◦ Is it reasonable that a reader could view my work differently if they knew I chose to
analyze a variable related to revenue when I could have analyzed a variables related
to profit? Yes, so it’s worth mentioning I chose this specific variable and not
another.
◦ Is it reasonable that a reader could view my work differently if they knew I renamed
the variables from all capitals to all lower case? Definitely not

## Results

Results: A hypothesis test set up to address your research questions(s). You should
interpret the results in the context of the data explain their relevance. If you are using a
regression model in your analysis, each of it’s coefficients should be clearly explained.
You should include negative results, but be careful about how you interpret them. For
example, you may want to say something along the lines of: “we found no evidence
that explanatory variable x is associated with response variable y,” or “explanatory
variable x did not provide any additional explanatory power above what was already
conveyed by explanatory variable z”. On other hand, you probably shouldn’t claim:
“there is no relationship between x and y”.

## Discussion

Discussion/Conclusion: a summary of your findings and a discussion of their
limitations. Be sure to remind the reader of the question that you originally set out to
answer, and summarize your answer to the question. Your discussion should also
protect yourself against misinterpretation by being clear about what is not implied by
your research. Finally, you should also discuss the limitations of your analysis and/or
data, and how it could be augmented or improved with future research. This “future
questions” portion of the discussion should include a brief exploratory analysis
showing how your project could be extended to include additional explanatory
variables in the future.

### Conclusions

### Limitations

### Further Questions

#### Appendix 

Appendix (Potentially Optional): If you have any supplemental analyses that would be
of interest (e.g., examining the assumptions of your two-sample t-test), you may wish
to place those analyses in an appendix at the end of your report.

#### Bibliography

Bibliography: Your report should contain at least two references (one of those
references must be the source of your data). You can use any reasonable citation style
(e.g., APA or MLA format), but regardless of style, your bibliography should clearly
identify the primary source you are referencing.

There is no limit to the length of the technical report, but it should not be longer than it needs
to be; you should strive to express your ideas concisely and precisely in all situations. Even
though you are expected to write your technical report as an Rmarkdown or Quarto document,
the PDF and HTML file you submit should not display any R code, warnings, or messages.
Your technical report should also be well formatted and well organized (e.g., using properly
formatted headers to divide sections, using LaTeX markup for mathematical symbols where
needed, tables should have bolded column and row labels, etc.).
